// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrT9WyqegFTzLedUXntMq-VN2ErSrvUDg',
    appId: '1:1036118706231:web:86f0ef3f56cdfc272c57b2',
    messagingSenderId: '1036118706231',
    projectId: 'atria-assignment',
    authDomain: 'atria-assignment.firebaseapp.com',
    storageBucket: 'atria-assignment.firebasestorage.app',
    measurementId: 'G-MRSGG4S4VH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcTkg0elVlq9CUYm-iFqxgI2rybqwUCC8',
    appId: '1:1036118706231:android:1cf5f9fbc43bb3d22c57b2',
    messagingSenderId: '1036118706231',
    projectId: 'atria-assignment',
    storageBucket: 'atria-assignment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDn00WFmo9jwjJkNsQO4JvhmcogbaMGso',
    appId: '1:1036118706231:ios:56c03baefa58f9902c57b2',
    messagingSenderId: '1036118706231',
    projectId: 'atria-assignment',
    storageBucket: 'atria-assignment.firebasestorage.app',
    iosBundleId: 'com.example.atriaAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDn00WFmo9jwjJkNsQO4JvhmcogbaMGso',
    appId: '1:1036118706231:ios:56c03baefa58f9902c57b2',
    messagingSenderId: '1036118706231',
    projectId: 'atria-assignment',
    storageBucket: 'atria-assignment.firebasestorage.app',
    iosBundleId: 'com.example.atriaAssignment',
  );
}
